name: Testapalooza

on: pull_request

jobs:

  build:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.17
      uses: actions/setup-go@v3
      with:
        go-version: 1.17
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
      
    - name: Run test
      run: |
        make test
    
    - name: Run docs examples
      run: |
        make docs/examples/test
